--- 
build: 
  script: 
    - rm -rf output
    - pelican content
  stage: build
  tags: 
    - ci
    - shell
    - ssh

deploy:
  script:
    - cd output;nohup python -m pelican.server &
  stage: deploy
  tags:
    - ci
    - shell
    - ssh
  when: manual

stages: 
  - build
  - deploy
